#!/bin/bash

build() {
	add_all_modules ethernet
	add_binary ip
	add_binary dhclient
	add_binary dhclient-script
	add_binary traceroute
	add_binary netstat
	add_binary ss
	add_file /etc/resolv.conf
	# prefer real chown over busybox
	add_binary chown

    add_binary "$recipes_root/recipes/ez_net/ez_net_start.sh" /ez_recipes/ez_net/ez_net_start.sh

	add_file "$recipes_root/recipes/ez_net/ez_net.sh" /ez_recipes/ez_net/ez_net.sh 755
	add_symlink /libexec/hooks/early-setup.d/ez_net.sh /ez_recipes/ez_net/ez_net.sh
}
