#!/bin/bash

build() {
	add_binary setfont
	add_binary showconsolefont
    #TODO include just the font we want
	add_full_dir /usr/share/kbd

	# shellcheck disable=SC2154
	add_file "$recipes_root/recipes/ez_consolefont/ez_console.sh" /ez_recipes/ez_consolefont/ez_console.sh 755
	add_symlink /libexec/hooks/early-setup.d/ez_console.sh /ez_recipes/ez_consolefont/ez_console.sh
}
