xbps-packages:
  - ncurses
  - strace
  - gum
  - yq-go
  - htop
  - file
  - busybox-huge
  - util-linux
  - pciutils
  - lshw
debian-packages:
  - kbd
help: "Required common dependencies to all recipes"
