#!/bin/bash

build() {
	# shellcheck disable=SC2154
	for pushover in "$recipes_root/ez_webttyd_pushover.conf" "$recipes_root/build/ez_webttyd_pushover.conf" "/var/lib/ez_webttyd/ez_webttyd_pushover.conf"; do
		[[ -f "$pushover" ]] && break
	done

	if [ ! -r "$pushover" ]; then
		warning "Pushover config not found"
	else 
		echo "Adding pushoever secrets ${pushover} to image"
		add_file "$pushover" /var/lib/ez_webttyd/ez_webttyd_pushover.conf
	fi

	add_binary ttyd
	add_binary timeout

	add_file "$recipes_root/recipes/ez_webttyd/ez_webttyd_start.sh" /ez_recipes/ez_webttyd/ez_webttyd_start.sh 755
	add_file "$recipes_root/recipes/ez_webttyd/ez_webttyd_up" /ez_recipes/ez_webttyd/ez_webttyd_up 755
	add_symlink /ez_recipes/ez_ifup.d/ez_webttyd_up /ez_recipes/ez_webttyd/ez_webttyd_up

	add_file "$recipes_root/recipes/ez_webttyd/ez_webttyd_down" /ez_recipes/ez_webttyd/ez_webttyd_down 755
	add_symlink /libexec/hooks/teardown.d/ez_webttyd_down /ez_recipes/ez_webttyd/ez_webttyd_down
}
