#!/bin/bash

start_getty() {
    if [[ -e "$1" ]]; then
        while true; do
            ( exec setsid getty -n -l  0 "$1" > /dev/kmsg 2>&1 )
        done 
    fi
}

trap '' EXIT INT TERM
#tput clear


# read all configured consoles
read -r active < /sys/class/tty/console/active

# start prelogin on all consoles
for c in ${active}; do
    start_getty "/dev/${c}" /init.prelogin &
done

# wait for prelogin tasks to finish
wait 

# read active consoles into array
read -r -a secondary <<< "$active"
# last item in list is the one connected to /dev/console and is considered
# the "main" console
console=${secondary[-1]}
# remove last
unset 'secondary[-1]'

# start login on secondary console
for c in "${secondary[@]}"; do
    start_getty "/dev/${c}" /zquick/init &
done

# start login on primary console
start_getty "/dev/${console}" /zquick/init

#this magic will redirect everything to another term
#bash -i -l 2>&1 | tee /dev/tty1