#!/bin/bash

mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sys /sys -o nosuid,noexec,nodev
mount -t devtmpfs dev /dev -o mode=0755,nosuid
mount -t tmpfs run /run -o nosuid,nodev,mode=0755

if [ -e /sys/firmware/efi ]; then
    mount -t efivarfs efivarfs /sys/firmware/efi/efivars -o nosuid,nodev,noexec
fi

# Setup /dev symlinks
if [ -e /proc/kcore ]; then
    ln -sfT /proc/kcore /dev/core
fi
ln -sfT /proc/self/fd /dev/fd
ln -sfT /proc/self/fd/0 /dev/stdin
ln -sfT /proc/self/fd/1 /dev/stdout
ln -sfT /proc/self/fd/2 /dev/stderr

mkdir -p /var/log
touch /var/log/messages
syslogd
klogd -c 4
udevd --daemon --resolve-names=never
udevadm trigger --action=add --type=subsystems
udevadm trigger --action=add --type=devices

hooks="/lib/zfsbootmenu-parse-commandline.sh /lib/zfsbootmenu-preinit.sh"

# for hook in ${hooks}; do
#     [ -r "${hook}" ] && . "${hook}" && continue

#     echo "ERROR: failed to load hook "${hook}"; good luck..."
#     getty -n -l /bin/sh 0 /dev/ttyS0
# done

# ( exec setsid getty -n -l /zquick/init 0 /dev/ttyS0 & )
# ( exec setsid getty -n -l /zquick/init 0 /dev/hvc0 & )
# ( exec setsid getty -n -l /zquick/init 0 /dev/ttyUSB0 & )

# getty -n -l /zquick/init 0 /dev/tty1

bash