#!/bin/bash



build() {

	zquick_add_secret /var/lib/tailscale/tailscaled.state "tailscale node identity"
	zquick_add_secret /etc/tailscale/tailscaled.conf "tailscale config"

	zquick_add_fs
	
	#tailscale ssh needs to be able to lookup users
	add_binary getent

	add_binary tailscaled
	add_binary tailscale
	add_binary iptables
	add_binary ip6tables
	add_binary pgrep
	add_symlink "/usr/bin/pkill" "pgrep"
	
	# add_full_dir /usr/share/ca-certificates
	# add_dir /etc/ssl/certs
	add_file /etc/ca-certificates.conf
	add_binary openssl
	add_file /etc/ssl/openssl.cnf
	add_binary update-ca-certificates
	add_file /etc/ssl/certs/ca-certificates.crt
	add_symlink /etc/ssl/cert.pem /etc/ssl/certs/ca-certificates.crt

	add_symlink /usr/lib/ssl/cert.pem /etc/ssl/cert.pem
	add_symlink /usr/lib/ssl/certs /etc/ssl/certs
	add_symlink /usr/lib/ssl/openssl.cnf /etc/ssl/openssl.cnf
	add_symlink /usr/lib/ssl/private /etc/ssl/private

	# chroot "${BUILDROOT}" /bin/bash -c "update-ca-certificates" > /dev/null
	# chroot "${BUILDROOT}" /bin/bash -c "mv /etc/ssl/certs/ca-certificates.crt /tmp; rm -rf /etc/ssl/certs/* /usr/share/ca-certificates /etc/ca-certificates.conf /usr/sbin/update-ca-certificates; mkdir -p /etc/ssl/certs;  mv /tmp/ca-certificates.crt /etc/ssl/certs/" > /dev/null
	# add_symlink /etc/ssl/cert.pem /etc/ssl/certs/ca-certificates.crt

	add_full_dir /usr/lib/xtables
	add_full_dir /usr/lib/x86_64-linux-gnu/xtables
	add_module tun
	add_all_modules netfilter
}
