#!/bin/bash

build() {
	zquick_add_fs

	add_binary clear
	add_binary reset
	add_binary strace
	if which yq-go >/dev/null; then
		add_binary yq-go
	else
		add_binary yq
	fi
	add_binary gum
	add_binary htop

	# user info
	add_file /etc/passwd
	add_file /etc/group
	add_file /etc/shells

	cat >> "${BUILDROOT}/root/.bashrc" <<-'EOF'
		PATH="$PATH":/zquick
		export TERM='xterm-256color'
		alias ls='ls --color=auto' 
		alias grep='grep --colour=auto'
		for h in /zquick/hooks/bash.d/*; do
			[ -x "${h}" ] || continue
			source "${h}"
		done
		EOF

	add_binary usermod
	chroot "${BUILDROOT}" usermod --shell /bin/bash root

	# create wrapper for zfsbootmenu entry point
	cp "${BUILDROOT}/libexec/zfsbootmenu-initcpio" "${BUILDROOT}/libexec/zfsbootmenu-initcpio.original"
	rm "${BUILDROOT}/libexec/zfsbootmenu-initcpio"
 	cat > "${BUILDROOT}/libexec/zfsbootmenu-initcpio" <<-'EOF'
		#!/bin/bash
		echo "Triggering uevents..."
		udevadm trigger --action=add --type=subsystems
		udevadm trigger --action=add --type=devices
		udevadm settle
		echo "Triggering ddd..."
		exec bash /libexec/zfsbootmenu-initcpio.original
		EOF
    chmod 755 "${BUILDROOT}/libexec/zfsbootmenu-initcpio"
	
	# UDEV stuff
	add_file "/etc/udev/udev.conf"
    add_binary /usr/bin/udevd
    add_binary /usr/bin/udevadm

    for rule in 50-udev-default.rules 60-persistent-storage.rules 64-btrfs.rules 80-drivers.rules; do
	echo $rule
        add_file "/usr/lib/udev/rules.d/$rule"
    done

    for tool in ata_id scsi_id; do
        add_file "/usr/lib/udev/$tool"
    done
	# end UDEV
	add_runscript
}
# https://pkginfo.devuan.org/cgi-bin/package-query.html?c=package&q=eudev=3.2.14-1
