#!/bin/bash



build() {
	add_full_dir /usr/share/terminfo
	[[ -d /lib/terminfo ]] && add_full_dir /lib/terminfo

	if [ -e "/usr/lib/locale/locale-archive" ]; then
		add_file "/usr/lib/locale/locale-archive" "/usr/lib/locale/locale-archive"
	fi

	zquick_add_fs 
	add_binary tmux
	
}
