#!/bin/sh
# Note: no runtime hooks are run when using systemd

run_earlyhook() {
    mkdir -p /var/log
    touch /var/log/messages
    syslogd
    klogd -c 4

    udevd --daemon --resolve-names=never
    udevd_running=1

    echo "Triggering uevents..."
    udevadm trigger --action=add --type=subsystems
    udevadm trigger --action=add --type=devices
}

run_hook() {
	exec /bin/bash /libexec/zfsbootmenu-initcpio
}
