#!/bin/bash

name=$(basename "$0")
log() {
   logger -p user.notice -t "${name}" "$1"
}

if [ ! -r /var/lib/tailscale/tailscaled.state ]; then 
	log "Tailscale SKIPPED"
	exit 0
fi

# create pts if not available
if [ ! -d /dev/pts ]; then
	mkdir -p /dev/pts
	mount -t devpts devpts /dev/pts
fi

# shellcheck disable=SC1091
[ -r /etc/tailscale/tailscaled.conf ] && . /etc/tailscale/tailscaled.conf

mkdir -p /var/log
modprobe tun
(exec setsid tailscaled --statedir=/var/lib/tailscale > /var/log/tailscale.log 2>&1 &)

# shellcheck disable=SC2086,2154
if tailscale up --reset --ssh --timeout="${tailscale_timeout:-20s}" $tailscale_args ; then
	  log "Tailscale OK"
else
	  log "Tailscale FAILED"
fi