#!/bin/bash

build() {
	add_full_dir /usr/share/terminfo

	if [ -e "/usr/lib/locale/locale-archive" ]; then
		add_file "/usr/lib/locale/locale-archive" "/usr/lib/locale/locale-archive"
	fi

	cat > ${BUILDROOT}/etc/tmux.conf <<-EOF

		set -g default-shell /bin/bash
		set -g history-limit 5000
		set -g base-index 1           # start windows numbering at 1
		setw -g pane-base-index 1     # make pane numbering consistent with windows

		setw -g automatic-rename on   # rename window to reflect current program
		set -g renumber-windows on    # renumber windows when a window is closed

		set -g set-titles on          # set terminal title

		set -g display-panes-time 800 # slightly longer pane indicators display time
		set -g display-time 1000      # slightly longer status messages display time

		set -g status-interval 1      # redraw status line every second

		######################
		### DESIGN CHANGES ###
		######################

		# loud or quiet?
		set -g visual-activity off
		set -g visual-bell off
		set -g visual-silence off
		setw -g monitor-activity off
		set -g bell-action none

		#  modes
		setw -g clock-mode-colour colour5
		setw -g mode-style 'fg=colour1 bg=colour18 bold'

		# panes
		set -g pane-border-style 'fg=colour19 bg=colour0'
		set -g pane-active-border-style 'bg=colour0 fg=colour9'

		# statusbar
		set -g status-position bottom
		set -g status-justify left
		set -g status-style 'bg=colour18 fg=colour137 dim'
		set -g status-left ''
		set -g status-right '#(/ez_recipes/ez_tmux/ez_tmux_status.sh)'
		set -g status-right-length 100
		set -g status-left-length 20

		setw -g window-status-current-style 'fg=colour1 bg=colour19 bold'
		setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour255]#W#[fg=colour249]#F '

		setw -g window-status-style 'fg=colour9 bg=colour18'
		setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

		setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'

		# messages
		set -g message-style 'fg=colour232 bg=colour16 bold'
		EOF

	add_file "$recipes_root/recipes/ez_tmux/ez_tmux_status.sh" /ez_recipes/ez_tmux/ez_tmux_status.sh 755
	add_binary tmux
	
	# patch the pre-init
	echo "Note: patching /lib/zfsbootmenu-preinit.sh to run within tmux"
	sed -i '/^exec/d' ${BUILDROOT}/lib/zfsbootmenu-preinit.sh
	cat >> ${BUILDROOT}/lib/zfsbootmenu-preinit.sh <<-'EOF'
		if [ ! -d /dev/pts ]; then
			mkdir -p /dev/pts
			mount -t devpts devpts /dev/pts
		fi
		function attach {
			tmux new-session -A -s ZFSBootMenu /libexec/zfsbootmenu-init
		}
		# prevent badness if detaching tmux from real term
		trap attach EXIT
		while true; do
			attach
		done
		EOF

	# make bash sessions automatically join tmux sessions
	cat >> ${BUILDROOT}/root/.bashrc <<-'EOF'
		if [[ -z $TMUX ]]; then
			tmux a
		fi
		EOF

	add_binary chsh
	chroot "${BUILDROOT}" /bin/bash -c "chsh -s /bin/bash"
}
