#!/bin/bash

wrap_user() {
	U=$(id -u)
	G=$(id -g)

	HOME_DIR=/tmp/user
	PASSWD=/var/tmp/passwd
	GROUP=/var/tmp/group

	if [ ! -d "$HOME_DIR" ]; then
		mkdir "$HOME_DIR"
	fi
	if [ ! -f "$PASSWD" ]; then
		echo "user::$U:$G::$HOME_DIR:" >"$PASSWD"
	fi
	if [ ! -f "$GROUP" ]; then
		echo "user::$G:" >"$GROUP"
	fi

	LD_PRELOAD=libnss_wrapper.so NSS_WRAPPER_PASSWD="$PASSWD" NSS_WRAPPER_GROUP="$GROUP" "$@"
}
build() {
	zquick_add_fs

	add_binary sshd
	add_file /usr/libexec/sshd-session

	zquick_add_secret /root/.ssh/authorized_keys "sshd authorized_keys for root" 644

	zquick_add_secret /etc/ssh/ssh_host_rsa_key "sshd host rsa key" 600
	zquick_add_secret /etc/ssh/ssh_host_ecdsa_key "sshd host ecdsa key" 600
	zquick_add_secret /etc/ssh/ssh_host_ed25519_key "sshd host ed25519 key" 600

	zquick_add_secret /etc/ssh/ssh_host_rsa_key.pub "sshd host rsa pub key" 644
	zquick_add_secret /etc/ssh/ssh_host_ecdsa_key.pub "sshd host ecdsa pub key" 644
	zquick_add_secret /etc/ssh/ssh_host_ed25519_key.pub "sshd host ed25519 pub key" 644

	zquick_add_secret /etc/ssh/sshd_config "sshd configuration" 644

	if [[ ! -e "${BUILDROOT}/etc/ssh/ssh_host_rsa_key" && ! -e "${BUILDROOT}/etc/ssh/ssh_host_ecdsa_key" && ! -e "${BUILDROOT}/etc/ssh/ssh_host_ed25519_key" ]]; then
		msg2 "NOTICE: No host keys specified, autogenerating new keys for this build. Keys will be not be saved to zquickinit configuration area."
		wrap_user ssh-keygen -A -f "${BUILDROOT}"
	fi

	if [[ ! -e "${BUILDROOT}/etc/ssh/sshd_config" ]]; then
		msg2 "sshd_config not found, sshd will likely not run until this file is present. (Can be injected into image later)"
	elif [[ ! -e "${BUILDROOT}/root/.ssh/authorized_keys" ]]; then
		msg2 "NOTICE: /root/.ssh/authorized_keys not found."
	fi

}
