#!/bin/bash

build() {
	add_binary df
	add_binary du
	add_binary which
	add_binary gdisk
	add_binary parted
	add_binary wipefs
	add_binary kpartx
	add_binary sgdisk
	add_binary mkfs.ext4
	add_binary mkfs.vfat
	add_binary efibootmgr
	add_binary cryptsetup
}
