#!/bin/bash

build() {
	# shellcheck disable=SC2154
	for state in "$recipes_root/tailscaled.state" "$recipes_root/build/tailscaled.state" "/var/lib/tailscale/tailscaled.state"; do
		[[ -f "$state" ]] && break
	done

	if [ ! -r "$state" ]; then
		warning "Tailscale node data (tailscaled.state) not found during build time."
	else 
		echo "Adding tailscale secrets ${state} to image"
		add_file "$state" /var/lib/tailscale/tailscaled.state
	fi

	add_file "$recipes_root/recipes/ez_tailscale/ez_tailscale_up" /ez_recipes/ez_tailscale/ez_tailscale_up 755
	add_symlink /ez_recipes/ez_ifup.d/ez_tailscale_up /ez_recipes/ez_tailscale/ez_tailscale_up

	add_file "$recipes_root/recipes/ez_tailscale/ez_tailscale_down" /ez_recipes/ez_tailscale/ez_tailscale_down 755
	add_symlink /ez_recipes/reboot.d/ez_tailscale_down /ez_recipes/ez_tailscale/ez_tailscale_down

	add_binary getent

	#tailscale ssh needs to be able to lookup users
	add_file /etc/passwd
	add_file /etc/group
	add_file /etc/shells

	add_binary tailscaled
	add_binary tailscale
	add_binary iptables
	add_binary ip6tables
	
	add_full_dir /usr/share/ca-certificates
	add_dir /etc/ssl/certs
	add_file /etc/ca-certificates.conf
	add_binary update-ca-certificates
	add_binary openssl
	chroot "${BUILDROOT}" /bin/bash -c "update-ca-certificates"

	add_full_dir /usr/lib/xtables
	add_module tun
	add_all_modules netfilter

	[ -r "/etc/tailscale/tailscaled.conf" ] && add_file /etc/tailscale/tailscaled.conf 
}
