#!/bin/bash

build() {
    zquick_add_fs

    local mod
    local symlink

    # device mapper modules
    for mod in dm-mod dm-snapshot dm-mirror dm-cache dm-cache-smq dm-thin-pool; do
        add_module "$mod"
    done

    # binaries from lvm2
    add_binary "lvm"
    if which lvmetad >/dev/null 2>&1; then
        add_binary "lvmetad"
    fi

    # binaries from device-mapper
    add_binary "dmsetup"

    # from thin-provisioning-tools
    add_binary "pdata_tools"
    for symlink in cache_{check,dump,metadata_size,repair,restore} thin_{check,delta,dump,ls,metadata_size,repair,restore,rmap,trim}; do
        add_symlink "/usr/bin/${symlink}" "pdata_tools"
    done

    # udev rules and lvm configuration
    # the first is in arch/void, the 2nd is in debian-based
    [[ -e /usr/lib/udev/rules.d/10-dm.rules ]] && add_udev_rule /usr/lib/udev/rules.d/10-dm.rules
    [[ -e /usr/lib/udev/rules.d/55-dm.rules ]] && add_udev_rule /usr/lib/udev/rules.d/55-dm.rules

    [[ -e /usr/lib/udev/rules.d/11-dm-lvm.rules ]] && add_udev_rule /usr/lib/udev/rules.d/11-dm-lvm.rules
    [[ -e /usr/lib/udev/rules.d/56-lvm.rules ]] && add_udev_rule /usr/lib/udev/rules.d/56-lvm.rules

    [[ -e /usr/lib/udev/rules.d/13-dm-disk.rules ]] && add_udev_rule /usr/lib/udev/rules.d/13-dm-disk.rules
    [[ -e /usr/lib/udev/rules.d/60-persistent-storage-dm.rules ]] && add_udev_rule /usr/lib/udev/rules.d/60-persistent-storage-dm.rules

    add_udev_rule "/usr/lib/udev/rules.d/95-dm-notify.rules"

    [[ -e /usr/lib/initcpio/udev/11-dm-initramfs.rules ]] && add_udev_rule /usr/lib/initcpio/udev/11-dm-initramfs.rules
    [[ -e /usr/lib/initcpio/udev/69-dm-lvm-metad.rules ]] && add_udev_rule /usr/lib/initcpio/udev/69-dm-lvm-metad.rules

    add_file "/etc/lvm/lvm.conf"

}
