#!/bin/bash

build() {
	for hostname in "$recipes_root/hostname" "$recipes_root/build/hostname" "/etc/hostname"; do
		[[ -f "$hostname" ]] && break
	done

	if [ ! -r "$hostname" ]; then
		warning "Hostname not found"
	else 
		add_file "$hostname" /etc/hostname
	fi

	add_file "$recipes_root/recipes/ez_hostname/ez_hostname.sh" /ez_recipes/ez_hostname/ez_hostname.sh 755
	add_symlink /libexec/hooks/early-setup.d/ez_hostname.sh /ez_recipes/ez_hostname/ez_hostname.sh
}
