#!/bin/bash

trap "echo 'Poweroff interrupted.'; exit 1" INT SIGINT

function reboot {
    echo "Poweroff..."
    for i in 3 2 1; do
        echo $i
        sleep 1
    done

    echo "Unmounting filesystems"
    pools=$(zpool list -H -o name)
    for pool in $pools; do
        zpool export "$pool"
    done
   
    echo "Running reboot hooks"
    /zquick/libexec/run_hooks.sh reboot.d

    echo "Poweroff"
    sleep 0.5s
    echo s > /proc/sysrq-trigger
    echo u > /proc/sysrq-trigger
    echo o > /proc/sysrq-trigger
}

reboot
