#!/bin/bash

# Always execute login (Which sets the HOME directory to the value in /etc/passwd).
#
# login will launch the shell (bash) which will
# auto-launch zfsbootmenu which requires access to the terminal, so it
# will be delayed until after login. If there is no root password, login will
# automatically login as root user.
#
# When using tmux support, tmux will automatically start zfsbootmenu
# on a virtual terminal and login will attach to that virtual terminal.
# see recipes/zquick_tmux/fs/zquick/init for more info.

#tput clear
cat <<EOF
                                                                                         
 _|_|_|_|_|                      _|            _|        _|_|_|            _|    _|      
       _|      _|_|_|  _|    _|        _|_|_|  _|  _|      _|    _|_|_|        _|_|_|_|  
     _|      _|    _|  _|    _|  _|  _|        _|_|        _|    _|    _|  _|    _|      
   _|        _|    _|  _|    _|  _|  _|        _|  _|      _|    _|    _|  _|    _|      
 _|_|_|_|_|    _|_|_|    _|_|_|  _|    _|_|_|  _|    _|  _|_|_|  _|    _|  _|      _|_|  
                   _|                                                                    
                   _|                                                                    


EOF

if [[ -f "/etc/zfsbootmenu.conf" ]]; then
  source /etc/zfsbootmenu.conf
fi

echo The controlling terminal is ${control_term}
echo This terminal is $(tty)
echo

read -n 1 -s -r -p $'Press any key to login\n\n'
exec login

# sleep 10
# clear
# passwd=$(sed -r '/root/{s/[^:]*:([^:]*).*/\1/;t};d' /etc/passwd)
# if (( ${#passwd} >= 2 )); then
#     exec login
# else
#     sleep 10
#     export HOME=/root
#     exec /libexec/zfsbootmenu-init
# fi
